services:
  bemol_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "bemol_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - bemol_rabbitmq
    restart: unless-stopped

networks:
  bemol_rabbitmq:
    driver: bridge
volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
