services:
  bemol_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "bemol_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_postgres:
    container_name: bemol_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-bemol}
      PGDATA: /data/postgres
    volumes:
      - bemol_postgres_vol:/data/postgres
    ports:
      - "5454:5432"
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_pgadmin:
    container_name: bemol_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-jander.webmaster@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - bemol_pgadmin_vol:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5052}:80"
    networks:
      - bemol_network
    restart: unless-stopped

  minio:
    container_name: bemol_minio
    image: docker.io/bitnami/minio:2022
    ports:
      - "9002:9000"
      - "9003:9001"
    networks:
      - bemol_network
    volumes:
      - "bemol_minio_data:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=bemol

networks:
  bemol_network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
  bemol_postgres_vol:
  bemol_pgadmin_vol:
  bemol_minio_data:
