services:
  bemol_bff:
    container_name: bemol_bff
    build:
      context: ./bemol-bff-gateway
    ports:
      - "4546:4546"
    env_file:
      - ./bemol-bff-gateway/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
    networks:
      - bemol_network
    restart: unless-stopped

  orders_microservice:
    container_name: orders_microservice
    build:
      context: ./orders-microservice
    ports:
      - "4500:4500"
    env_file:
      - ./orders-microservice/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
      - sendmail_microservice
    networks:
      - bemol_network
    restart: unless-stopped

  products_microservice:
    container_name: products_microservice
    build:
      context: ./products-microservice
    ports:
      - "4549:4549"
    env_file:
      - ./products-microservice/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
      - sendmail_microservice
      - orders_microservice
    networks:
      - bemol_network
    restart: unless-stopped

  inventory_microservice:
    container_name: inventory_microservice
    build:
      context: ./inventory-microservice
    ports:
      - "4503:4503"
    env_file:
      - ./inventory-microservice/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
      - sendmail_microservice
      - orders_microservice
    networks:
      - bemol_network
    restart: unless-stopped

  payment_microservice:
    container_name: payment_microservice
    build:
      context: ./payment-microservice
    ports:
      - "4442:4442"
    env_file:
      - ./payment-microservice/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
      - sendmail_microservice
      - orders_microservice
    networks:
      - bemol_network
    restart: unless-stopped

  sendmail_microservice:
    container_name: sendmail_microservice
    build:
      context: ./mail-microservice
    ports:
      - "5533:5533"
    env_file:
      - ./mail-microservice/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
    networks:
      - bemol_network
    restart: unless-stopped

  payment_gateway:
    container_name: payment_gateway
    build:
      context: ./payment-gateway
    ports:
      - "5560:5560"
    env_file:
      - ./payment-gateway/.env
    depends_on:
      - bemol_postgres_products
      - bemol_postgres_inventory
      - bemol_postgres_orders
      - bemol_postgres_payments
      - bemol_rabbitmq
      - bemol_bff
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "bemol_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_postgres_products:
    container_name: bemol_postgres_products
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-bemol}
      PGDATA: /data/postgres
    volumes:
      - bemol_postgres_products_vol:/data/postgres
    ports:
      - "5454:5432"
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_postgres_inventory:
    container_name: bemol_postgres_inventory
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-bemol}
      PGDATA: /data/postgres
    volumes:
      - bemol_postgres_inventory_vol:/data/postgres
    ports:
      - "5457:5432"
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_postgres_orders:
    container_name: bemol_postgres_orders
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-bemol}
      PGDATA: /data/postgres
    volumes:
      - bemol_postgres_orders_vol:/data/postgres
    ports:
      - "5456:5432"
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_postgres_payments:
    container_name: bemol_postgres_payments
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-bemol}
      PGDATA: /data/postgres
    volumes:
      - bemol_postgres_payments_vol:/data/postgres
    ports:
      - "5455:5432"
    networks:
      - bemol_network
    restart: unless-stopped

  bemol_pgadmin:
    container_name: bemol_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-jander.webmaster@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - bemol_pgadmin_vol:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5052}:80"
    networks:
      - bemol_network
    restart: unless-stopped

  minio:
    container_name: bemol_minio
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - bemol_network
    volumes:
      - "bemol_minio_data:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=bemol
    restart: unless-stopped

networks:
  bemol_network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
  bemol_postgres_vol:
  bemol_pgadmin_vol:
  bemol_minio_data:
  bemol_postgres_orders_vol:
  bemol_postgres_payments_vol:
  bemol_postgres_products_vol:
  bemol_postgres_inventory_vol:
