@startuml Code n4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(orderServiceAndProcess, "Order Service and Process") {
    Component(orderController, "OrderController", "Controller", "Recebe requisições HTTP relacionadas a pedidos")
    Component(orderRepository, "OrderRepository", "Repository", "Realiza operações de persistência de pedidos e Publica Eventos para os Microserviços")
    Component(orderService, "OrderService", "Business Logic", "Chama o Repository, Persiste na Base de Dados e Publica Eventos para os Microserviços")

}

  ContainerDb(database, "Database", "PostgreSQL", "Armazena o estado dos produtos")
  Container(broker, "Message Broker", "RabbitMQ", "Centraliza a troca de mensagens entre serviços")




Rel(broker, orderController, "Processa eventos de pedidos consumidos do Message Broker")
Rel(orderService, broker, "Processa eventos de pedidos consumidos do Message Broker")
Rel(orderController, orderService, "Envia a Mensagem do Broker ou a Chamada da Api para tualização do estado dos pedidos")
Rel(orderService, orderRepository, "Contem a Logica de acesso a camada de persistencia do Banco de Dados")
Rel(orderRepository, database, "Armazena estado de pedidos")

@enduml
