@startuml Code n4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(inventoryServiceAndProcess, "Inventory Service and Process") {
    Component(inventoryController, "Inventory Controller", "Controller", "Recebe requisições HTTP relacionadas ao inventário e Recebe eventos de estoque consumidos do Message Broker")  
    Component(inventoryRepository, "Inventory Repository", "Repository", "Realiza operações de persistência de pedidos")
    Component(inventoryService, "Inventory Service", "Business Logic", "Chama o Repository e Persiste na Base de Dados")
}

 Container(broker, "Message Broker", "RabbitMQ", "Centraliza a troca de mensagens entre serviços")
ContainerDb(database, "Database", "PostgreSQL", "Armazena o estado dos pagamentos")

Rel(broker, inventoryController, "Processa eventos de estoque consumidos do Message Broker")
Rel(inventoryController, inventoryService, "Chama para processar os dados de inventário")
Rel(inventoryService, inventoryRepository, "Contem a Logica de acesso a camada de persistencia do Banco de Dados")
Rel(inventoryService, broker, "Processa eventos de estoque consumidos do Message Broker")
Rel(inventoryRepository, database, "Armazena estado de pagamentos")

@enduml
