apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-bemol
  labels:
    app: bff-bemol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff-bemol
  template:
    metadata:
      labels:
        app: bff-bemol
    spec:
      containers:
      - name: bff-bemol
        image: jandernery/bemol_bff_gateway:v1.0
        ports:
        - containerPort: 4545

---
apiVersion: v1
kind: Service
metadata:
  name: bff-bemol
spec:
  selector:
    app: bff-bemol
  ports:
    - port: 4545
      targetPort: 4545