apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemol-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bemol-minio
  template:
    metadata:
      labels:
        app: bemol-minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: bemol-minio-service
spec:
  selector:
    app: bemol-minio
  ports:
    - name: minio-port
      port: 9000
      targetPort: 9000
    - name: minio-console-port
      port: 9001
      targetPort: 9001
  type: ClusterIP
