apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672  # Porta de comunicação
        - containerPort: 15672 # Porta de gerenciamento (opcional)
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-log
          mountPath: /var/log/rabbitmq
      volumes:
      - name: rabbitmq-data
        emptyDir: {}  # Em produção, pode ser alterado para um volume persistente (PVC)
      - name: rabbitmq-log
        emptyDir: {}  # Também pode ser um PVC
